Repository mitre/hipcheck, pull requests merged in 2024-07, with the labels that each got.

#167 feat: Added `--env` flag to `xtask site serve`
  xtask/src/main.rs
  xtask/src/task/site/serve.rs
Labels: type: enhancement

#168 fix: Correct broken links throughout the site.
  site/templates/macros/breadcrumbs.tera.html
  site/templates/partials/footer.tera.html
  site/templates/partials/nav.tera.html
Labels: type: bug

#170 Weight Tree Printing
  hipcheck/src/analysis/score.rs
  hipcheck/src/cli.rs
  hipcheck/src/main.rs
  hipcheck/src/shell.rs
Labels: type: enhancement, type: ui

#173 feat: Improved the site homepage and install instructions.
  site/content/_index.md
  site/content/install/_index.md
  site/static/images/homepage-bg.png
  site/tailwind.config.js
  site/templates/bases/base.tera.html
  site/templates/index.html
  site/templates/shortcodes/info.html
  xtask/src/task/site/serve.rs
Labels: type: enhancement

#174 feat: Completed the install instructions and Quickstart guide.
  site/content/docs/_index.md
  site/content/docs/quickstart/_index.md
  site/content/install/_index.md
  site/content/rfds/0000-rfds.md
  site/content/rfds/_index.md
  site/templates/bases/base.tera.html
  site/templates/shortcodes/button.html
Labels: type: enhancement

#177 fix: Vendor libgit2 and openssl so that hipcheck builds in containers more consistently.
  Cargo.lock
  hipcheck/Cargo.toml
Labels: type: bug

#176 feat: Adds hc update command
  Cargo.lock
  hipcheck/src/cli.rs
  hipcheck/src/main.rs
Labels: type: enhancement

#178 chore: Update cargo-dist to version 0.17.0
  .github/workflows/release.yml
  Cargo.toml
Labels: type: chore, dependencies

#179 feat: More website improvements.
  site/content/docs/guide/_index.md
  site/content/docs/guide/analyses.md
  site/content/docs/guide/concepts.md
  site/content/docs/guide/configuration.md
  site/content/docs/guide/debugging.md
  site/content/docs/guide/how-to-use.md
  site/content/docs/guide/logging.md
  site/content/docs/guide/targets.md
  site/content/docs/guide/why.md
  site/templates/index.html
  site/templates/shortcodes/button.html
Labels: type: enhancement

#188 feat: Completed MVP of Hipcheck Complete Guide
  site/content/docs/guide/_index.md
  site/content/docs/guide/analyses.md
  site/content/docs/guide/concepts.md
  site/content/docs/guide/concepts/concepts-diagram.svg
  site/content/docs/guide/concepts/index.md
  site/content/docs/guide/concepts/score-tree-final.svg
  site/content/docs/guide/concepts/score-tree-pct.svg
  site/content/docs/guide/concepts/score-tree.svg
  site/content/docs/guide/configuration.md
  site/content/docs/guide/debugging.md
  site/content/docs/guide/how-to-use.md
  site/content/docs/guide/logging.md
  site/content/docs/guide/targets.md
  site/content/docs/guide/why.md
Labels: type: enhancement

#189 fix: Fix broken website links in production.
  site/config.toml
  site/templates/index.html
  site/templates/partials/footer.tera.html
  site/templates/partials/nav.tera.html
Labels: type: bug

#190 fix: Fix more broken links.
  site/content/docs/_index.md
  site/content/docs/guide/why.md
  site/content/docs/quickstart/_index.md
  site/content/install/_index.md
  site/templates/shortcodes/button.html
Labels: type: bug

#200 chore (deps): Update cargo-dist to v0.18.0-prerelease1
  .github/workflows/release.yml
  Cargo.toml
Labels: dependencies

#205 feat(CLI): CLI can infer target type from target pURL
  Cargo.lock
  hipcheck/Cargo.toml
  hipcheck/src/cli.rs
  hipcheck/src/target.rs
Labels: type: enhancement

#198 feat: Shell rework
  Cargo.lock
  hipcheck/Cargo.toml
  hipcheck/src/analysis/score.rs
  hipcheck/src/benchmarking.rs
  hipcheck/src/cli.rs
  hipcheck/src/main.rs
  hipcheck/src/session/session.rs
  hipcheck/src/shell.rs
  hipcheck/src/shell/color_choice.rs
  hipcheck/src/shell/iter.rs
  hipcheck/src/shell/macros.rs
  hipcheck/src/shell/par_iter.rs
  hipcheck/src/shell/prelude.rs
  hipcheck/src/shell/progress_phase.rs
  hipcheck/src/shell/spinner_phase.rs
  hipcheck/src/shell/verbosity.rs
  hipcheck/src/source/source.rs
Labels: type: enhancement, type: ui

#221 fix: Add missing step to install instructions
  site/content/install/_index.md
Labels: type: bug

#223 chore: Refactor duplicate agent definitions.
  hipcheck/src/data/github/mod.rs
  hipcheck/src/git2_rustls_transport.rs
  hipcheck/src/http.rs
  hipcheck/src/http/agent.rs
  hipcheck/src/http/authenticated_agent.rs
  hipcheck/src/http/tls.rs
  hipcheck/src/session/pm.rs
  hipcheck/src/setup.rs
  hipcheck/src/util.rs
  hipcheck/src/util/hidden.rs
Labels: type: chore

#228 feat: make conf-not-found error message suggest use of `hc setup`
  hipcheck/src/session/session.rs
Labels: type: bug, type: ui

#227 feat: add more robust 'target resolution' system
  Cargo.lock
  hipcheck/src/cli.rs
  hipcheck/src/main.rs
  hipcheck/src/session/pm.rs
  hipcheck/src/session/session.rs
  hipcheck/src/source.rs
  hipcheck/src/source/query.rs
  hipcheck/src/source/source.rs
  hipcheck/src/target.rs
  hipcheck/src/target/types.rs
Labels: type: enhancement

#229 chore(refactor): remove use of Source, SourceRepo, Remote structs
  hipcheck/src/data/query/github.rs
  hipcheck/src/source.rs
  hipcheck/src/source/query.rs
  hipcheck/src/source/source.rs
  hipcheck/src/target.rs
Labels: type: chore

#225 chore: Replace log bridge dependency with bespoke implementation
  Cargo.lock
  hipcheck/Cargo.toml
  hipcheck/src/log_bridge.rs
  hipcheck/src/main.rs
  hipcheck/src/shell.rs
Labels: type: chore

#224 feat: add `hc cache` subcommand for manually listing/deleting elements of the cache
  Cargo.lock
  hipcheck/Cargo.toml
  hipcheck/src/cache.rs
  hipcheck/src/cli.rs
  hipcheck/src/main.rs
  hipcheck/src/metric/typo.rs
Labels: type: enhancement, type: ui

#236 feat: shortcut cache entry size calculation with cache index file
  hipcheck/src/cache.rs
  hipcheck/src/main.rs
Labels: type: enhancement

#237 feat: Hipcheck can process SBOMs using CycloneDX JSONs
  Cargo.lock
  hipcheck/Cargo.toml
  hipcheck/src/cli.rs
  hipcheck/src/session.rs
  hipcheck/src/session/cyclone_dx.rs
  hipcheck/src/session/pm.rs
  hipcheck/src/session/session.rs
  hipcheck/src/session/spdx.rs
  hipcheck/src/session/tests/juiceshop_bom.json
  hipcheck/src/target.rs
  hipcheck/src/target/types.rs
Labels: type: enhancement

#238 fix: Hipcheck now works with scoped npm packages.
  hipcheck/src/cli.rs
  hipcheck/src/session/pm.rs
  hipcheck/src/target.rs
Labels: type: bug

#240 feat: update remote-repo updating to support git refs
  hipcheck/src/cli.rs
  hipcheck/src/main.rs
  hipcheck/src/session/session.rs
  hipcheck/src/source/git.rs
  hipcheck/src/source/source.rs
  hipcheck/src/target/types.rs
Labels: type: enhancement

#241 fix: correct language in the description of HcCache::drop
  hipcheck/src/cache.rs
Labels: type: chore

#242 feat: update local-repo copying to support git refs
  hipcheck/src/cli.rs
  hipcheck/src/source/source.rs
Labels: type: bug
