Repository mitre/hipcheck, pull requests merged in 2024-05, with the labels that each got.

#42 fix: Remove 'atty' dep for GHSA-g98v-hv3f-hcfr
  Cargo.lock
  libs/hc_shell/Cargo.toml
  libs/hc_shell/src/lib.rs
Labels: type: bug

#43 Feat: Move metrics related crates into `hc_metric`
  Cargo.lock
  libs/hc_binary/Cargo.toml
  libs/hc_linguist/Cargo.toml
  libs/hc_math/Cargo.toml
  libs/hc_metric/Cargo.toml
  libs/hc_metric/src/binary.rs
  libs/hc_metric/src/binary_detector/mod.rs
  libs/hc_metric/src/binary_detector/query.rs
  libs/hc_metric/src/churn.rs
  libs/hc_metric/src/entropy.rs
  libs/hc_metric/src/lib.rs
  libs/hc_metric/src/linguist/mod.rs
  libs/hc_metric/src/linguist/query.rs
  libs/hc_metric/src/math.rs
  libs/hc_session/Cargo.toml
  libs/hc_session/src/lib.rs
Labels: type: enhancement

#44 feat: Move hc_pm into hc_session
  Cargo.lock
  libs/hc_common/src/lib.rs
  libs/hc_pm/Cargo.toml
  libs/hc_session/Cargo.toml
  libs/hc_session/src/lib.rs
  libs/hc_session/src/pm.rs
Labels: type: enhancement

#45 feat: Creates a single analysis crate that handles most of the Hipcheck analysis pipeline
  Cargo.lock
  hipcheck/Cargo.toml
  hipcheck/src/main.rs
  libs/hc_analysis/Cargo.toml
  libs/hc_analysis/src/analysis.rs
  libs/hc_analysis/src/lib.rs
  libs/hc_analysis/src/metric/activity.rs
  libs/hc_analysis/src/metric/affiliation.rs
  libs/hc_analysis/src/metric/binary.rs
  libs/hc_analysis/src/metric/binary_detector/mod.rs
  libs/hc_analysis/src/metric/binary_detector/query.rs
  libs/hc_analysis/src/metric/churn.rs
  libs/hc_analysis/src/metric/commit_trust.rs
  libs/hc_analysis/src/metric/contributor_trust.rs
  libs/hc_analysis/src/metric/entropy.rs
  libs/hc_analysis/src/metric/fuzz.rs
  libs/hc_analysis/src/metric/identity.rs
  libs/hc_analysis/src/metric/linguist/mod.rs
  libs/hc_analysis/src/metric/linguist/query.rs
  libs/hc_analysis/src/metric/math.rs
  libs/hc_analysis/src/metric/mod.rs
  libs/hc_analysis/src/metric/module.rs
  libs/hc_analysis/src/metric/module_contributors.rs
  libs/hc_analysis/src/metric/review.rs
  libs/hc_analysis/src/metric/typo.rs
  libs/hc_analysis/src/report_builder.rs
  libs/hc_analysis/src/score.rs
  libs/hc_analysis/src/session/mod.rs
  libs/hc_analysis/src/session/pm.rs
  libs/hc_analysis/src/session/spdx.rs
  libs/hc_core/Cargo.toml
  libs/hc_core/src/lib.rs
  libs/hc_metric/Cargo.toml
  libs/hc_report_builder/Cargo.toml
  libs/hc_score/Cargo.toml
  libs/hc_session/Cargo.toml
  libs/hc_spdx/Cargo.toml
Labels: type: enhancement

#52 Add missing license notices.
  hipcheck/src/data/github/authenticated_agent.rs
  hipcheck/src/data/github/hidden.rs
Labels: type: chore

#51 Fix double-version command in `xtask`
  .cargo/config.toml
  xtask/src/main.rs
Labels: type: bug

#50 Removed dead code.
  hipcheck/src/data.rs
  hipcheck/src/data/es_lint/mod.rs
  hipcheck/src/data/git/mod.rs
  hipcheck/src/data/query/mod.rs
  hipcheck/src/error.rs
  hipcheck/src/filesystem.rs
  hipcheck/src/main.rs
  hipcheck/src/report.rs
  hipcheck/src/shell.rs
  hipcheck/src/test_util.rs
Labels: type: chore

#48 Added "Release Engineering" RFD
  docs/rfds/0001-release-engineering.md
Labels: type: enhancement

#41 feat: Add 'cargo-dist' for prebuilt binaries.
  .github/workflows/release.yml
  Cargo.toml
  hipcheck/Cargo.toml
Labels: type: enhancement

#54 chore: Added basic community docs.
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE
  scripts/module-deps.js
Labels: type: enhancement

#58 Setup configuration for `CHANGELOG.md` generation.
  Cargo.toml
Labels: type: enhancement

#59 chore: Adds security policy
  SECURITY.md
Labels: type: chore

#60 fix: Fix broken `cargo-dist` build.
  .github/workflows/release.yml
  Cargo.toml
Labels: type: enhancement

#61 Improved `Cargo.toml` metadata, removed unused deps.
  Cargo.lock
  hipcheck/Cargo.toml
Labels: type: enhancement

#62 Improved 'xtask' experience, removed old commands.
  Cargo.lock
  xtask/Cargo.toml
  xtask/src/exit.rs
  xtask/src/main.rs
  xtask/src/task/bench.rs
  xtask/src/task/ci.rs
  xtask/src/task/doc.rs
  xtask/src/task/install.rs
  xtask/src/task/mod.rs
  xtask/src/task/validate.rs
  xtask/src/workspace.rs
Labels: type: enhancement

#63 add `xtask changelog` command.
  .cargo/config.toml
  .gitignore
  Cargo.lock
  Cargo.toml
  xtask/Cargo.toml
  xtask/src/main.rs
  xtask/src/task/changelog.rs
  xtask/src/task/check.rs
  xtask/src/task/ci.rs
  xtask/src/task/mod.rs
  xtask/src/workspace.rs
Labels: type: enhancement

#68 chore: Do not run tests if changes outside code folders
  .github/workflows/test.yml
Labels: type: chore

#70 Add "Hipcheck's Values" RFD
  docs/rfds/0002-hipcheck's-values.md
Labels: type: enhancement

#71 Added RFD #3, "Plugin Architecture Vision"
  docs/rfds/0002-hipchecks-values.md
  docs/rfds/0003-plugin-architecture-vision.md
Labels: type: enhancement

#72 fix: Removes missing /libs folder from Container file
  Containerfile
Labels: type: bug

#80 Chore: Remove OpenSSL as a Hipcheck dependency
  Cargo.lock
  Cargo.toml
  Containerfile
  docs/rfds/0001-release-engineering.md
  hipcheck/Cargo.toml
  hipcheck/src/analysis/session/pm.rs
  hipcheck/src/data/github/authenticated_agent.rs
Labels: type: chore

#89 fix: Change xtask validate to xtask check when xtask ci is called.
  xtask/src/task/ci.rs
Labels: type: bug

#81 feat: Adds hc ready command
  hipcheck/src/cli.rs
  hipcheck/src/main.rs
Labels: type: enhancement

#85 chore(http): Change `ureq` Agent to use native system certs
  Cargo.lock
  hipcheck/Cargo.toml
  hipcheck/src/data/github/authenticated_agent.rs
Labels: type: chore

#90 chore: Add license and description to rfd.rs
  xtask/src/task/rfd.rs
Labels: type: chore
