Repository mitre/hipcheck, pull requests merged in 2024-11, with the labels that each got.

#558 chore: Makes changes needed for affiliation plugin to run
  config/Hipcheck.kdl
  hipcheck/src/plugin/retrieval.rs
  plugins/affiliation/plugin.kdl
  plugins/affiliation/src/main.rs
  plugins/git/src/data.rs
  plugins/git/src/local.rs
  plugins/git/src/main.rs
Labels: type: chore, product: rust-sdk

#567 fix: Make Git parser handle meta lines in chunk
  plugins/git/src/main.rs
  plugins/git/src/parse.rs
Labels: type: bug

#577 Diff parser bugfixes
  plugins/git/src/main.rs
  plugins/git/src/parse.rs
Labels: type: bug

#581 fix: Tries refspec with leading "v" if it fails without one
  hipcheck/src/source/git.rs
Labels: type: bug, product: hc

#588 fix: change binary plugin to return val policy expr can understand
  hipcheck/src/policy/config_to_policy.rs
  hipcheck/src/policy/test_example.kdl
  plugins/binary/src/main.rs
Labels: type: bug

#589 fix: Fix injection logic for datetime and span
  hipcheck/src/policy_exprs/json_pointer.rs
Labels: product: hc

#591 fix: `hc cache` deletion logic
  hipcheck/src/cache/repo.rs
Labels: type: bug, product: hc

#597 chore: Adds e-mail to affiliated concern reporting
  hipcheck/src/source/git.rs
  plugins/affiliation/src/main.rs
  plugins/affiliation/test/example_orgs.kdl
Labels: type: chore, product: rust-sdk

#599 fix: bugs in detecting empty git diffs and end of patch meta block
  plugins/git/src/main.rs
  plugins/git/src/parse.rs
  plugins/git/src/util/git_command.rs
Labels: type: bug

#604 fix: remove double-printing of policy exprs
  hipcheck/src/report/mod.rs
  hipcheck/src/report/report_builder.rs
  hipcheck/src/shell/mod.rs
Labels: type: chore

#620 fix: erroneously changed default policy for binary
  plugins/binary/src/main.rs
Labels: type: bug

#621 fix: Fix broken script URLs on live site.
  site/scripts/src/footer/installer.ts
  site/static/js/footer.mjs
  site/static/js/footer.mjs.map
Labels: type: bug

#622 fix: Fix broken Containerfile
  dist/Containerfile
Labels: type: bug

#626 fix: handling of plugin entrypoint string
  hipcheck/src/plugin/manager.rs
  hipcheck/src/plugin/mod.rs
  hipcheck/src/plugin/plugin_manifest.rs
  hipcheck/src/plugin/retrieval.rs
Labels: type: bug, product: hc

#627 chore: rename typo-file-path and orgs-file-path
  config/Hipcheck.kdl
  plugins/affiliation/src/main.rs
  plugins/typo/src/main.rs
Labels: type: chore

#630 feat: improve chunking method in sdk
  hipcheck/src/plugin/types.rs
  sdk/rust/src/plugin_engine.rs
Labels: type: enhancement, product: hc, product: rust-sdk

#634 fix affiliation chunking and git plugin performance
  plugins/affiliation/src/main.rs
  plugins/git/src/data.rs
  plugins/git/src/local.rs
  plugins/git/src/main.rs
Labels: type: bug, product: hc, product: rust-sdk

#456 feat: add RF8 to describe policy expr internals refactor
  site/content/rfds/0008-policy-expr-typing-refactor.md
Labels: type: refactor, product: hc

#643 fix: add hash check when copying local plugins on windows
  hipcheck/src/plugin/retrieval.rs
  hipcheck/src/util/fs.rs
Labels: type: bug

#550 feat: add RFD describing proposed batched query feature
  site/content/docs/rfds/0009-batch-queries.md
  site/content/docs/rfds/0010-submit-chunking.md
Labels: type: enhancement, product: hc, product: rust-sdk
