Repository mitre/hipcheck, pull requests merged in 2024-09, with the labels that each got.

#325 fix: Broken release build for Hipcheck.
  hipcheck/Cargo.toml
  hipcheck/build.rs
  hipcheck/proto/hipcheck/v1/hipcheck.proto
  plugins/dummy_rand_data/build.rs
  plugins/dummy_sha256/build.rs
Labels: type: bug

#327 feat: introduce plugin-based query infrastructure to scoring
  .gitignore
  Cargo.lock
  hipcheck/Cargo.toml
  hipcheck/src/analysis/score.rs
  hipcheck/src/config.rs
  hipcheck/src/engine.rs
  hipcheck/src/metric/affiliation.rs
  hipcheck/src/metric/churn.rs
  hipcheck/src/metric/entropy.rs
  hipcheck/src/metric/identity.rs
  hipcheck/src/metric/review.rs
  hipcheck/src/metric/typo.rs
  hipcheck/src/plugin/mod.rs
  hipcheck/src/plugin/types.rs
  hipcheck/src/policy_exprs/mod.rs
  hipcheck/src/session/mod.rs
  hipcheck/src/target/types.rs
Labels: type: enhancement

#328 fix: Install the protobuf compiler in release CI
  Cargo.toml
Labels: type: bug

#331 fix: Copy plugins into containerfile build step
  Containerfile
Labels: type: bug

#330 feat: Adds structures and functions to parse policy files.
  hipcheck/src/kdl_helper.rs
  hipcheck/src/main.rs
  hipcheck/src/plugin/download_manifest.rs
  hipcheck/src/plugin/mod.rs
  hipcheck/src/plugin/plugin_manifest.rs
  hipcheck/src/policy/mod.rs
  hipcheck/src/policy/policy_file.rs
  hipcheck/src/policy/tests.rs
  hipcheck/src/policy_exprs/mod.rs
  hipcheck/src/session/mod.rs
Labels: type: enhancement

#333 fix: Adds weight field to policy file categories
  hipcheck/src/policy/policy_file.rs
  hipcheck/src/policy/tests.rs
Labels: type: bug

#332 chore: More CI jobs
  .github/workflows/docker.yml
  .github/workflows/hipcheck.yml
  .github/workflows/release-dry-run.yml
Labels: type: chore

#336 chore: Converts config file to policy file under the hood
  hipcheck/src/config.rs
  hipcheck/src/policy/config_to_policy.rs
  hipcheck/src/policy/mod.rs
  hipcheck/src/policy/test_example.kdl
  hipcheck/src/policy/tests.rs
  hipcheck/src/session/mod.rs
Labels: type: chore

#340 fix: Adds code to retrieve config information from policy file analyses.
  hipcheck/src/config.rs
  hipcheck/src/metric/affiliation.rs
  hipcheck/src/metric/binary_detector/query.rs
  hipcheck/src/metric/linguist/query.rs
  hipcheck/src/metric/typo.rs
  hipcheck/src/policy/policy_file.rs
Labels: type: enhancement, type: chore

#341 Jlanson/add concern
  hipcheck/proto/hipcheck/v1/hipcheck.proto
  hipcheck/src/analysis/score.rs
  hipcheck/src/config.rs
  hipcheck/src/engine.rs
  hipcheck/src/metric/affiliation.rs
  hipcheck/src/plugin/mod.rs
  hipcheck/src/plugin/types.rs
  hipcheck/src/policy/policy_file.rs
  hipcheck/src/report.rs
  plugins/dummy_rand_data/src/main.rs
  plugins/dummy_rand_data/src/transport.rs
  plugins/dummy_sha256/src/main.rs
  plugins/dummy_sha256/src/transport.rs
Labels: type: enhancement

#342 feat: Added PolicyFile::get_config method
  hipcheck/src/config.rs
  hipcheck/src/policy/mod.rs
  hipcheck/src/policy/policy_file.rs
Labels: type: enhancement

#339 chore (CLI): Deprecates the config arg
  hipcheck/src/cli.rs
  hipcheck/src/main.rs
  hipcheck/src/session/mod.rs
Labels: type: chore

#349 feat: Implement big chunk of the plugin system.
  config/Hipcheck.kdl
  hipcheck/proto/hipcheck/v1/hipcheck.proto
  hipcheck/src/analysis/mod.rs
  hipcheck/src/analysis/score.rs
  hipcheck/src/cache/plugin_cache.rs
  hipcheck/src/config.rs
  hipcheck/src/engine.rs
  hipcheck/src/main.rs
  hipcheck/src/metric/affiliation.rs
  hipcheck/src/metric/binary_detector/query.rs
  hipcheck/src/metric/commit_trust.rs
  hipcheck/src/metric/contributor_trust.rs
  hipcheck/src/metric/linguist/query.rs
  hipcheck/src/metric/typo.rs
  hipcheck/src/new_report_discussion.rs
  hipcheck/src/plugin/download_manifest.rs
  hipcheck/src/plugin/mod.rs
  hipcheck/src/plugin/plugin_id.rs
  hipcheck/src/plugin/plugin_manifest.rs
  hipcheck/src/plugin/retrieval.rs
  hipcheck/src/plugin/supported_arch.rs
  hipcheck/src/plugin/types.rs
  hipcheck/src/policy/config_to_policy.rs
  hipcheck/src/policy/mod.rs
  hipcheck/src/policy/policy_file.rs
  hipcheck/src/policy/tests.rs
  hipcheck/src/report.rs
  hipcheck/src/report_discussion.rs
  hipcheck/src/session/mod.rs
  hipcheck/src/util/fs.rs
  plugins/dummy_rand_data/src/main.rs
  plugins/dummy_rand_data/src/transport.rs
  plugins/dummy_sha256/src/main.rs
  plugins/dummy_sha256/src/transport.rs
  site/content/rfds/0004-plugin-api.md
Labels: type: enhancement

#361 feat: Add support for reporting plugin results.
  config/Hipcheck.kdl
  hipcheck/src/analysis/result.rs
  hipcheck/src/analysis/score.rs
  hipcheck/src/config.rs
  hipcheck/src/engine.rs
  hipcheck/src/plugin/mod.rs
  hipcheck/src/plugin/types.rs
  hipcheck/src/report/mod.rs
  hipcheck/src/report/report_builder.rs
  hipcheck/src/shell/mod.rs
Labels: type: enhancement

#362 fix: make HcEngine plugin lookup use {publisher}/{plugin} as key
  hipcheck/src/engine.rs
  hipcheck/src/main.rs
  hipcheck/src/plugin/mod.rs
  hipcheck/src/plugin/types.rs
  plugins/dummy_rand_data/src/main.rs
Labels: type: chore

#363 chore: Updated `CHANGELOG.md` for `3.6.1`
  CHANGELOG.md
Labels: type: chore

#368 chore: Added `CHANGELOG.md` entry for `3.6.2`
  CHANGELOG.md
Labels: type: chore

#373 fix: Remove scoring panic.
  hipcheck/src/analysis/score.rs
Labels: type: bug

#372 chore: Revert 'cargo-dist' workaround
  .github/workflows/mac-build-custom-setup.yml
  .github/workflows/release.yml
  Cargo.toml
Labels: type: chore

#375 feat: add divz policy-expr func and fix some policies in legacy config file conversion
  config/Hipcheck.kdl
  hipcheck/src/policy/config_to_policy.rs
  hipcheck/src/policy/test_example.kdl
  hipcheck/src/policy_exprs/env.rs
  hipcheck/src/policy_exprs/mod.rs
  hipcheck/src/report/report_builder.rs
Labels: type: bug, type: enhancement

#378 chore: Update `CHANGELOG.md` for `3.6.3`
  CHANGELOG.md
Labels: type: chore

#379 chore: Removing dead code
  hipcheck/src/data/es_lint/data.rs
  hipcheck/src/data/es_lint/mod.rs
  hipcheck/src/main.rs
  hipcheck/src/plugin/download_manifest.rs
  hipcheck/src/plugin/manager.rs
  hipcheck/src/plugin/mod.rs
  hipcheck/src/plugin/plugin_manifest.rs
  hipcheck/src/session/pm.rs
  hipcheck/src/source/mod.rs
Labels: type: refactor

#398 chore: Add HSSEDI contract number to the README.
  README.md
Labels: type: chore, product: project

#413 chore: Add GitHub privacy policy to website footer
  site/templates/partials/footer.tera.html
Labels: type: chore, product: website

#412 Introduce issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: type: chore, product: project

#414 chore: Update Containerfile
  .github/workflows/dockerhub.yml
  Containerfile
Labels: type: chore, product: release-flow

#417 chore: Update devcontainer definition
  .devcontainer/devcontainer.json
Labels: type: bug, product: project

#416 feat(xtask): Added 'buf' xtask subcommand
  .buf.yaml
  xtask/src/main.rs
  xtask/src/task/buf.rs
  xtask/src/task/mod.rs
Labels: type: enhancement, product: project

#426 feat: Make `xtask rfd new` include title in RFD file
  xtask/src/task/buf.rs
  xtask/src/task/rfd.rs
Labels: type: enhancement, product: project

#432 fix: Fix broken `Containerfile`
  dist/Containerfile
Labels: type: bug, product: release-flow

#433 feat: add --arch flag to `hc check` subcommand to allow detection override
  hipcheck/src/cli.rs
  hipcheck/src/engine.rs
  hipcheck/src/main.rs
  hipcheck/src/plugin/download_manifest.rs
  hipcheck/src/plugin/mod.rs
  hipcheck/src/plugin/supported_arch.rs
Labels: type: enhancement, product: hc

#430 chore: Simplify Release Procedures RFD
  site/content/rfds/0007-simplified-release-procedures.md
Labels: type: chore, product: release-flow

#440 chore: extend API doc comments for Rust SDK
  plugins/dummy_rand_data_sdk/src/main.rs
  sdk/rust/src/error.rs
  sdk/rust/src/lib.rs
  sdk/rust/src/plugin_engine.rs
  sdk/rust/src/plugin_server.rs
Labels: type: chore

#441 feat: Adds operators for datetime and span policy expression primitives
  hipcheck/src/policy_exprs/env.rs
  hipcheck/src/policy_exprs/error.rs
  hipcheck/src/policy_exprs/expr.rs
  hipcheck/src/policy_exprs/token.rs
Labels: type: enhancement, product: hc

#450 chore: add hipcheck::target::Target schema to Rust SDK
  Cargo.lock
  hipcheck/Cargo.toml
  hipcheck/src/target/types.rs
  sdk/rust/schema/hipcheck_target_schema.json
Labels: type: chore, product: rust-sdk

#455 fix: update target json desc from RootSchema to SchemaObject
  sdk/rust/schema/hipcheck_target_schema.json
Labels: type: bug, type: chore, product: rust-sdk

#452 feat: Adds query sdk proc-macro
  Cargo.lock
  Cargo.toml
  hipcheck-sdk-macros/Cargo.toml
  hipcheck-sdk-macros/src/lib.rs
  plugins/dummy_sha256_sdk/Cargo.toml
  plugins/dummy_sha256_sdk/src/main.rs
  sdk/rust/Cargo.toml
  sdk/rust/src/error.rs
  sdk/rust/src/lib.rs
Labels: type: enhancement, product: rust-sdk

#448 chore (doc): Adds date and time information to Plugin RFD
  hipcheck/src/policy_exprs/env.rs
  hipcheck/src/policy_exprs/expr.rs
  hipcheck/src/policy_exprs/token.rs
  site/content/rfds/0004-plugin-api.md
Labels: type: chore, product: website, product: project
