Repository mitre/hipcheck, pull requests merged in 2024-08, with the labels that each got.

#243 chore(refactor): distinguish TargetSeed and TargetSeedKind
  hipcheck/src/cli.rs
  hipcheck/src/main.rs
  hipcheck/src/session/pm.rs
  hipcheck/src/session/session.rs
  hipcheck/src/target/types.rs
Labels: type: chore

#244 feat: add --ref support to remaining target seed kinds
  hipcheck/src/cli.rs
  hipcheck/src/session/session.rs
  hipcheck/src/source/git.rs
  hipcheck/src/source/source.rs
  hipcheck/src/target/types.rs
Labels: type: enhancement

#245 feat: add commit info to hc cache display and index file
  hipcheck/src/cache.rs
Labels: type: enhancement

#251 chore: Update CHANGELOG.md for 3.5.0
  CHANGELOG.md
Labels: type: chore

#263 Fix website, announce 3.5.0
  site/config.toml
  site/content/rfds/0004-plugin-api.md
Labels: type: chore

#267 Fix broken containerfile.
  Containerfile
Labels: type: bug

#255 docs: added README for dockerhub
  .github/workflows/push-to-docker.yml
  dist/dockerhub/README.md
Labels: type: chore

#264 CI improvements
  .github/workflows/commits.yml
  .github/workflows/dockerhub.yml
  .github/workflows/hipcheck.yml
  .github/workflows/website-deploy.yml
  .github/workflows/website-test.yml
Labels: type: chore

#277 feat: add proto-file based code gen
  .github/workflows/hipcheck.yml
  Cargo.lock
  Containerfile
  hipcheck/Cargo.toml
  hipcheck/build.rs
  hipcheck/proto/hipcheck.proto
  hipcheck/src/.gitignore
  hipcheck/src/main.rs
  site/content/install/_index.md
Labels: type: enhancement

#278 feat: initial plugin startup and context management
  Cargo.lock
  hipcheck/Cargo.toml
  hipcheck/src/main.rs
  hipcheck/src/plugin/manager.rs
  hipcheck/src/plugin/mod.rs
  hipcheck/src/plugin/types.rs
Labels: type: enhancement

#281 Plugin initialization and aggregation
  Cargo.lock
  hipcheck/Cargo.toml
  hipcheck/src/plugin/manager.rs
  hipcheck/src/plugin/mod.rs
  hipcheck/src/plugin/types.rs
Labels: type: enhancement

#291 chore: Update cargo-dist to 0.21.0
  .github/workflows/release.yml
  Cargo.toml
Labels: type: chore

#294 feat (cli): Adds new --policy flag to Hipcheck
  hipcheck/src/cli.rs
  hipcheck/src/main.rs
  hipcheck/src/session/session.rs
Labels: type: enhancement

#290 Add dummy plugin and CLI to execute for testing
  Cargo.lock
  Cargo.toml
  hipcheck/Cargo.toml
  hipcheck/src/cli.rs
  hipcheck/src/main.rs
  hipcheck/src/plugin/manager.rs
  hipcheck/src/plugin/mod.rs
  hipcheck/src/plugin/types.rs
  plugins/dummy_rand_data/Cargo.toml
  plugins/dummy_rand_data/src/hipcheck.rs
  plugins/dummy_rand_data/src/hipcheck_transport.rs
  plugins/dummy_rand_data/src/main.rs
  plugins/dummy_rand_data/src/query_schema_get_rand.json
Labels: type: enhancement, type: ui

#297 feat: plugin interface handles multiple active query sessions
  Cargo.lock
  hipcheck/src/plugin/mod.rs
  hipcheck/src/plugin/types.rs
Labels: type: enhancement

#265 Integrate policy expressions code
  Cargo.lock
  hipcheck/Cargo.toml
  hipcheck/src/main.rs
  hipcheck/src/policy_exprs/bridge.rs
  hipcheck/src/policy_exprs/env.rs
  hipcheck/src/policy_exprs/error.rs
  hipcheck/src/policy_exprs/expr.rs
  hipcheck/src/policy_exprs/mod.rs
  hipcheck/src/policy_exprs/token.rs
Labels: type: chore

#298 plugin Salsa integration
  hipcheck/src/engine.rs
  hipcheck/src/main.rs
  hipcheck/src/plugin/mod.rs
  hipcheck/src/plugin/types.rs
Labels: type: enhancement

#307 feat: update dummy plugin to handle concurrent queries
  Cargo.lock
  hipcheck/src/engine.rs
  hipcheck/src/main.rs
  plugins/dummy_rand_data/Cargo.toml
  plugins/dummy_rand_data/src/hipcheck_transport.rs
  plugins/dummy_rand_data/src/main.rs
Labels: type: enhancement

#310 chore: Use consistent module folder structure.
  hipcheck/src/analysis/mod.rs
  hipcheck/src/cache/mod.rs
  hipcheck/src/data/mod.rs
  hipcheck/src/metric/mod.rs
  hipcheck/src/session/mod.rs
  hipcheck/src/shell/mod.rs
  hipcheck/src/source/mod.rs
  hipcheck/src/target/mod.rs
Labels: type: refactor

#311 chore: No more "module-inception"
  hipcheck/src/analysis/analysis.rs
  hipcheck/src/analysis/mod.rs
  hipcheck/src/analysis/report_builder.rs
  hipcheck/src/analysis/score.rs
  hipcheck/src/cache/mod.rs
  hipcheck/src/cli.rs
  hipcheck/src/data/git/query/mod.rs
  hipcheck/src/data/query/code_quality.rs
  hipcheck/src/data/query/dependencies.rs
  hipcheck/src/data/query/github.rs
  hipcheck/src/main.rs
  hipcheck/src/metric/metric.rs
  hipcheck/src/metric/mod.rs
  hipcheck/src/session/mod.rs
  hipcheck/src/session/session.rs
  hipcheck/src/source/mod.rs
  hipcheck/src/source/source.rs
Labels: type: refactor

#312 chore: Remove unused version handling
  hipcheck/build.rs
  hipcheck/src/main.rs
  hipcheck/src/session/mod.rs
  hipcheck/src/version.rs
Labels: type: refactor

#313 chore: Create new 'init' top-level module
  hipcheck/src/init/git2_log_shim.rs
  hipcheck/src/init/git2_rustls_transport.rs
  hipcheck/src/init/indicatif_log_bridge.rs
  hipcheck/src/init/mod.rs
  hipcheck/src/main.rs
Labels: type: refactor

#314 chore: Simplify .gitignore
  .gitignore
  hipcheck/src/.gitignore
Labels: type: refactor

#318 chore: Include `build.rs` in `hipcheck` crate
  hipcheck/Cargo.toml
Labels: type: chore
