Repository mitre/hipcheck, pull requests merged in 2024-12, with the labels that each got.

#681 chore: Updates file path tags in example policy file
  config/Hipcheck.kdl
Labels: type: chore, product: rust-sdk

#685 chore: Update site to new URL
  CHANGELOG.md
  README.md
  dist/dockerhub/README.md
  hipcheck/Cargo.toml
  site/config.toml
  site/content/docs/rfds/0004-plugin-api.md
  site/content/docs/rfds/0006-rust-plugin-sdk.md
  site/content/docs/rfds/0008-policy-expr-typing-refactor.md
  site/content/docs/rfds/0009-batch-queries.md
  site/content/docs/rfds/0010-submit-chunking.md
  site/scripts/src/footer/installer.ts
  site/static/js/footer.mjs
  site/static/js/footer.mjs.map
Labels: product: website

#608 chore: Preparing to use 'dist' for more releases.
  .github/workflows/release-dry-run.yml
  .github/workflows/release.yml
  Cargo.toml
  dist-workspace.toml
  hipcheck/Cargo.toml
  hipcheck/dist.toml
  plugins/activity/Cargo.toml
  plugins/activity/dist.toml
  plugins/activity/local-plugin.kdl
  plugins/activity/plugin.kdl
  plugins/affiliation/Cargo.toml
  plugins/affiliation/dist.toml
  plugins/affiliation/local-plugin.kdl
  plugins/affiliation/plugin.kdl
  plugins/binary/Cargo.toml
  plugins/binary/dist.toml
  plugins/binary/local-plugin.kdl
  plugins/binary/plugin.kdl
  plugins/churn/Cargo.toml
  plugins/churn/dist.toml
  plugins/churn/local-plugin.kdl
  plugins/churn/plugin.kdl
  plugins/entropy/Cargo.toml
  plugins/entropy/dist.toml
  plugins/entropy/local-plugin.kdl
  plugins/entropy/plugin.kdl
  plugins/fuzz/Cargo.toml
  plugins/fuzz/dist.toml
  plugins/fuzz/local-plugin.kdl
  plugins/fuzz/plugin.kdl
  plugins/git/Cargo.toml
  plugins/git/dist.toml
  plugins/git/local-plugin.kdl
  plugins/git/plugin.kdl
  plugins/github/Cargo.toml
  plugins/github/dist.toml
  plugins/github/local-plugin.kdl
  plugins/github/plugin.kdl
  plugins/identity/Cargo.toml
  plugins/identity/dist.toml
  plugins/identity/local-plugin.kdl
  plugins/identity/plugin.kdl
  plugins/linguist/Cargo.toml
  plugins/linguist/dist.toml
  plugins/linguist/local-plugin.kdl
  plugins/linguist/plugin.kdl
  plugins/linguist/src/main.rs
  plugins/npm/Cargo.toml
  plugins/npm/dist.toml
  plugins/npm/local-plugin.kdl
  plugins/npm/plugin.kdl
  plugins/review/Cargo.toml
  plugins/review/dist.toml
  plugins/review/local-plugin.kdl
  plugins/review/plugin.kdl
  plugins/typo/Cargo.toml
  plugins/typo/dist.toml
  plugins/typo/local-plugin.kdl
  plugins/typo/plugin.kdl
  xtask/Cargo.toml
Labels: product: project

#686 chore: Eliminate CHANGELOG.md
  CHANGELOG.md
Labels: product: project

#687 fix: Ensure plugins have protoc installed for dist.
  plugins/activity/dist.toml
  plugins/affiliation/dist.toml
  plugins/binary/dist.toml
  plugins/churn/dist.toml
  plugins/entropy/dist.toml
  plugins/fuzz/dist.toml
  plugins/git/dist.toml
  plugins/github/dist.toml
  plugins/identity/dist.toml
  plugins/linguist/dist.toml
  plugins/npm/dist.toml
  plugins/review/dist.toml
  plugins/typo/dist.toml
Labels: product: project

#691 feat: Add download manifests for all new plugins.
  site/static/dl/plugin/mitre/activity.kdl
  site/static/dl/plugin/mitre/affiliation.kdl
  site/static/dl/plugin/mitre/binary.kdl
  site/static/dl/plugin/mitre/churn.kdl
  site/static/dl/plugin/mitre/entropy.kdl
  site/static/dl/plugin/mitre/fuzz.kdl
  site/static/dl/plugin/mitre/git.kdl
  site/static/dl/plugin/mitre/github.kdl
  site/static/dl/plugin/mitre/identity.kdl
  site/static/dl/plugin/mitre/linguist.kdl
  site/static/dl/plugin/mitre/npm.kdl
  site/static/dl/plugin/mitre/review.kdl
  site/static/dl/plugin/mitre/typo.kdl
Labels: product: project

#695 fix: Fix plugin downloading and prep bump for fuzz
  config/Hipcheck.kdl
  hipcheck/src/plugin/download_manifest.rs
  hipcheck/src/plugin/plugin_manifest.rs
  hipcheck/src/plugin/retrieval.rs
  plugins/fuzz/plugin.kdl
Labels: type: bug, product: hc

#703 fix: misspelling in linux plugin download links
  site/static/dl/plugin/mitre/activity.kdl
  site/static/dl/plugin/mitre/affiliation.kdl
  site/static/dl/plugin/mitre/binary.kdl
  site/static/dl/plugin/mitre/churn.kdl
  site/static/dl/plugin/mitre/entropy.kdl
  site/static/dl/plugin/mitre/fuzz.kdl
  site/static/dl/plugin/mitre/git.kdl
  site/static/dl/plugin/mitre/github.kdl
  site/static/dl/plugin/mitre/identity.kdl
  site/static/dl/plugin/mitre/linguist.kdl
  site/static/dl/plugin/mitre/npm.kdl
  site/static/dl/plugin/mitre/review.kdl
  site/static/dl/plugin/mitre/typo.kdl
Labels: type: bug

#704 fix: get proper version from download manifest and spawn with canonical path
  config/local.Hipcheck.kdl
  hipcheck/src/engine.rs
  hipcheck/src/main.rs
  hipcheck/src/plugin/manager.rs
  hipcheck/src/plugin/plugin_manifest.rs
  hipcheck/src/plugin/retrieval.rs
  hipcheck/src/plugin/types.rs
Labels: type: bug, product: hc

#709 fix: update config to policy file conversion and associated tests
  hipcheck/src/cli.rs
  hipcheck/src/config.rs
  hipcheck/src/policy/config_to_policy.rs
  hipcheck/src/policy/test_example.kdl
Labels: type: bug, product: hc

#713 chore: 3.8.0 announcement post
  site/content/blog/2024-11-04-hipcheck-3.8.0-release.md
  site/templates/partials/prose-config.tera.html
Labels: product: website

#716 chore: Add ATProto DID for Bluesky username
  site/static/.well-known/atproto-did
Labels: product: website

#717 docs: Fixed spelling and updated link in docs
  site/content/docs/guide/config/policy-file.md
  site/content/docs/guide/plugins/mitre-entropy.md
Labels: status: needs-review, product: website

#725 chore: delete unused Salsa dbs in config.rs and clean up policy_exprs source
  hipcheck/src/config.rs
  hipcheck/src/main.rs
  hipcheck/src/policy_exprs/env.rs
  hipcheck/src/policy_exprs/expr.rs
  hipcheck/src/policy_exprs/mod.rs
  hipcheck/src/policy_exprs/pass.rs
  hipcheck/src/policy_exprs/token.rs
  hipcheck/src/session/mod.rs
Labels: type: chore

#693 feat: add `manifest` xtask to parse GitHub Release API output
  Cargo.lock
  xtask/Cargo.toml
  xtask/src/main.rs
  xtask/src/task/manifest/download_manifest.rs
  xtask/src/task/manifest/kdl.rs
  xtask/src/task/manifest/mod.rs
  xtask/src/task/manifest/release.rs
  xtask/src/task/manifest/remote.rs
  xtask/src/task/manifest/util/agent.rs
  xtask/src/task/manifest/util/authenticated_agent.rs
  xtask/src/task/manifest/util/mod.rs
  xtask/src/task/manifest/util/redacted.rs
  xtask/src/task/mod.rs
Labels: type: enhancement, type: ui, product: project

#744 feat(refactor): initial RFD5 impl, slight refspec handling improvement
  hipcheck/src/cli.rs
  hipcheck/src/session/mod.rs
  hipcheck/src/source/mod.rs
  hipcheck/src/target/mod.rs
  hipcheck/src/target/resolve.rs
  hipcheck/src/target/types.rs
Labels: type: enhancement, type: chore, product: hc
