Repository mitre/hipcheck, pull requests merged in 2024-06, with the labels that each got.

#93 Refactor CLI
  Cargo.lock
  Cargo.toml
  hipcheck-macros/Cargo.toml
  hipcheck-macros/README.md
  hipcheck-macros/src/lib.rs
  hipcheck-macros/src/update.rs
  hipcheck/Cargo.toml
  hipcheck/src/analysis/session/mod.rs
  hipcheck/src/analysis/session/spdx.rs
  hipcheck/src/cli.rs
  hipcheck/src/data/source/mod.rs
  hipcheck/src/main.rs
  hipcheck/src/report.rs
  hipcheck/src/shell.rs
Labels: type: enhancement

#116 chore: Move `metric` and `session` out of `analysis`
  hipcheck/src/analysis.rs
  hipcheck/src/analysis/analysis.rs
  hipcheck/src/analysis/report_builder.rs
  hipcheck/src/cli.rs
  hipcheck/src/main.rs
  hipcheck/src/metric.rs
  hipcheck/src/metric/activity.rs
  hipcheck/src/metric/affiliation.rs
  hipcheck/src/metric/binary.rs
  hipcheck/src/metric/binary_detector/mod.rs
  hipcheck/src/metric/binary_detector/query.rs
  hipcheck/src/metric/churn.rs
  hipcheck/src/metric/commit_trust.rs
  hipcheck/src/metric/contributor_trust.rs
  hipcheck/src/metric/entropy.rs
  hipcheck/src/metric/fuzz.rs
  hipcheck/src/metric/identity.rs
  hipcheck/src/metric/linguist/mod.rs
  hipcheck/src/metric/linguist/query.rs
  hipcheck/src/metric/math.rs
  hipcheck/src/metric/metric.rs
  hipcheck/src/metric/module.rs
  hipcheck/src/metric/module_contributors.rs
  hipcheck/src/metric/review.rs
  hipcheck/src/metric/typo.rs
  hipcheck/src/session.rs
  hipcheck/src/session/pm.rs
  hipcheck/src/session/session.rs
  hipcheck/src/session/spdx.rs
Labels: type: chore

#117 chore: Move `source` out of `data`
  hipcheck/src/analysis/report_builder.rs
  hipcheck/src/data.rs
  hipcheck/src/data/git/query/mod.rs
  hipcheck/src/data/query/code_quality.rs
  hipcheck/src/data/query/dependencies.rs
  hipcheck/src/data/query/github.rs
  hipcheck/src/main.rs
  hipcheck/src/session/session.rs
  hipcheck/src/source.rs
  hipcheck/src/source/query.rs
  hipcheck/src/source/source.rs
Labels: type: chore

#118 chore: Creates general `http` module for making requests
  hipcheck/src/data/github/code_search.rs
  hipcheck/src/data/github/graphql.rs
  hipcheck/src/data/github/graphql_pr.rs
  hipcheck/src/data/github/mod.rs
  hipcheck/src/http.rs
  hipcheck/src/http/authenticated_agent.rs
  hipcheck/src/http/hidden.rs
  hipcheck/src/http/tls.rs
  hipcheck/src/main.rs
  hipcheck/src/session/pm.rs
Labels: type: chore

#127 refactor: added new types to form the basis of scoring refactor
  Cargo.lock
  hipcheck/Cargo.toml
  hipcheck/src/analysis.rs
  hipcheck/src/analysis/analysis.rs
  hipcheck/src/analysis/report_builder.rs
  hipcheck/src/analysis/result.rs
  hipcheck/src/analysis/score.rs
  hipcheck/src/data/es_lint/data.rs
  hipcheck/src/data/modules.rs
  hipcheck/src/main.rs
Labels: type: enhancement

#135 chore: Make `cargo-dist` releases include `config/` and `scripts/`
  Cargo.toml
Labels: type: chore

#137 chore: Upgrade `cargo-dist` to 0.16.0
  .github/workflows/release.yml
  Cargo.toml
Labels: type: chore

#130 chore: Demonstrate use of hashmap with new result objects for analysis storage
  hipcheck/src/analysis/analysis.rs
  hipcheck/src/analysis/report_builder.rs
  hipcheck/src/analysis/result.rs
  hipcheck/src/analysis/score.rs
Labels: type: chore

#145 Remove unused tempdir dependency
  Cargo.lock
  hipcheck/Cargo.toml
Labels: dependencies

#147 Remove dependency on lazy_static.
  Cargo.lock
  hipcheck/Cargo.toml
  hipcheck/src/metric/typo.rs
  hipcheck/src/test_util.rs
Labels: dependencies

#146 feat: Parallelize grapheme collection across files.
  hipcheck/src/metric/entropy.rs
Labels: type: enhancement

#153 chore: Removes patch type as option
  hipcheck/src/cli.rs
  hipcheck/src/main.rs
  hipcheck/src/session/session.rs
  hipcheck/src/target.rs
Labels: type: chore

#157 chore: refactor all remaining repo analyses
  hipcheck/src/analysis/analysis.rs
  hipcheck/src/analysis/report_builder.rs
  hipcheck/src/analysis/result.rs
  hipcheck/src/analysis/score.rs
Labels: type: chore

#158 chore: remove pr analysis and scoring infrastructure
  hipcheck/src/analysis/analysis.rs
  hipcheck/src/analysis/report_builder.rs
  hipcheck/src/analysis/score.rs
  hipcheck/src/cli.rs
  hipcheck/src/config.rs
  hipcheck/src/main.rs
  hipcheck/src/metric.rs
  hipcheck/src/metric/affiliation.rs
  hipcheck/src/metric/contributor_trust.rs
  hipcheck/src/metric/metric.rs
  hipcheck/src/metric/module_contributors.rs
  hipcheck/src/report.rs
  hipcheck/src/session/session.rs
  hipcheck/src/shell.rs
Labels: type: chore

#155 feat: Slightly modified arguments for `hc setup`.
  hipcheck/src/cli.rs
Labels: type: enhancement, type: ui

#159 chore: replace prior AnalysisResults obj with AltAnalysisResults impl
  hipcheck/src/analysis/report_builder.rs
  hipcheck/src/analysis/score.rs
Labels: type: chore

#160 feat: add weight tree and replace old scoring
  Cargo.lock
  hipcheck/Cargo.toml
  hipcheck/src/analysis/report_builder.rs
  hipcheck/src/analysis/score.rs
  hipcheck/src/config.rs
  hipcheck/src/session/session.rs
Labels: type: enhancement

#128 Update the README
  README.md
  install.sh
Labels: type: chore

#161 chore: Add GitHub Action for site deployment.
  .github/workflows/website.yml
Labels: type: chore
