Repository mitre/hipcheck, pull requests merged in 2024-10, with the labels that each got.

#473 feat: add Rust SDK macro to auto-impl Plugin::queries() func
  hipcheck-sdk-macros/src/lib.rs
  plugins/dummy_sha256_sdk/src/main.rs
  sdk/rust/src/lib.rs
Labels: type: enhancement, product: rust-sdk

#266 Add RFD #5: Target Resolution Refactor
  site/content/rfds/0005-target-resolution-refactor.md
  site/content/rfds/0007-simplified-release-procedures.md
Labels: type: chore

#476 feat: add "mock_engine" feature to SDK to allow offline query testing
  plugins/dummy_rand_data_sdk/Cargo.toml
  plugins/dummy_rand_data_sdk/schema/query_schema_get_rand.json
  plugins/dummy_rand_data_sdk/src/main.rs
  sdk/rust/Cargo.toml
  sdk/rust/src/lib.rs
  sdk/rust/src/mock.rs
  sdk/rust/src/plugin_engine.rs
Labels: type: enhancement, product: rust-sdk

#477 feat(refactor): Created plugin version of git queries
  Cargo.lock
  Cargo.toml
  plugins/git/Cargo.toml
  plugins/git/src/data.rs
  plugins/git/src/main.rs
  plugins/git/src/parse.rs
  plugins/git/src/util/command.rs
  plugins/git/src/util/git_command.rs
  plugins/git/src/util/mod.rs
Labels: type: enhancement, type: refactor, product: rust-sdk, product: project

#483 feat(refactor): Created a plugin version of the NPM dependency query
  Cargo.lock
  Cargo.toml
  plugins/npm_dependencies/Cargo.toml
  plugins/npm_dependencies/src/main.rs
  plugins/npm_dependencies/src/npm.rs
  plugins/npm_dependencies/src/util/command.rs
  plugins/npm_dependencies/src/util/fs.rs
  plugins/npm_dependencies/src/util/mod.rs
Labels: type: enhancement, type: refactor, product: rust-sdk, product: project

#458 refactor PolicyExpr to use Visitor Pattern
  hipcheck/src/policy_exprs/env.rs
  hipcheck/src/policy_exprs/expr.rs
  hipcheck/src/policy_exprs/json_pointer.rs
  hipcheck/src/policy_exprs/mod.rs
  hipcheck/src/policy_exprs/pass.rs
Labels: type: chore, type: refactor, product: hc

#488 fix: PluginEngine::query not using inner function broadly enough
  sdk/rust/src/plugin_engine.rs
Labels: type: chore, product: rust-sdk

#487 feat: hc build emits target schemas, sdk interprets with typify
  Cargo.lock
  hipcheck/Cargo.toml
  hipcheck/build.rs
  hipcheck/src/target/mod.rs
  hipcheck/src/target/types.rs
  plugins/github_api/src/main.rs
  sdk/rust/Cargo.toml
  sdk/rust/schema/hipcheck_target_schema.json
  sdk/rust/src/lib.rs
  sdk/rust/src/types.rs
  sdk/schema/hipcheck_target_schema.json
Labels: type: enhancement, product: hc, product: rust-sdk

#481 fix: update language on handling of lambdas
  hipcheck/src/policy/config_to_policy.rs
  hipcheck/src/policy/test_example.kdl
  hipcheck/src/policy_exprs/env.rs
  site/content/docs/guide/plugin/policy-expr.md
Labels: product: hc

#500 feat: add fuzz plugin
  Cargo.lock
  Cargo.toml
  plugins/fuzz/Cargo.toml
  plugins/fuzz/src/main.rs
  plugins/github_api/src/data.rs
  sdk/rust/src/mock.rs
Labels: product: hc

#511 feat: enable SDK plugins to report concerns
  hipcheck-sdk-macros/src/lib.rs
  plugins/activity/Cargo.toml
  plugins/activity/src/main.rs
  plugins/dummy_rand_data_sdk/src/main.rs
  plugins/dummy_sha256_sdk/src/main.rs
  sdk/rust/src/plugin_engine.rs
Labels: type: enhancement, product: rust-sdk

#516 feat: Adds affiliation plugin.
  Cargo.lock
  Cargo.toml
  plugins/activity/src/main.rs
  plugins/affiliation/Cargo.toml
  plugins/affiliation/plugin.kdl
  plugins/affiliation/src/main.rs
  plugins/affiliation/src/org_spec.rs
  plugins/affiliation/src/org_types.rs
  plugins/affiliation/src/util/fs.rs
  plugins/affiliation/src/util/kdl.rs
  plugins/affiliation/src/util/mod.rs
  plugins/affiliation/test/example_orgs.kdl
  plugins/dummy_rand_data_sdk/src/main.rs
  plugins/fuzz/src/main.rs
  plugins/git/plugin.kdl
  sdk/rust/src/mock.rs
  sdk/rust/src/plugin_engine.rs
Labels: type: enhancement, product: rust-sdk

#519 feat: add Entropy plugin and Linguist plugin
  Cargo.lock
  Cargo.toml
  plugins/entropy/Cargo.toml
  plugins/entropy/src/error/context.rs
  plugins/entropy/src/error/mod.rs
  plugins/entropy/src/linguist/db.rs
  plugins/entropy/src/linguist/fs.rs
  plugins/entropy/src/linguist/mod.rs
  plugins/entropy/src/main.rs
  plugins/entropy/src/metric.rs
  plugins/entropy/src/types.rs
  plugins/linguist/Cargo.toml
  plugins/linguist/src/fs.rs
  plugins/linguist/src/linguist.rs
  plugins/linguist/src/main.rs
Labels: type: enhancement, product: hc

#521 feat: Adds review plugin
  Cargo.lock
  Cargo.toml
  plugins/github_api/plugin.kdl
  plugins/review/Cargo.toml
  plugins/review/plugin.kdl
  plugins/review/src/main.rs
Labels: type: enhancement, product: rust-sdk

#527 feat: added binary analysis plugin
  Cargo.lock
  Cargo.toml
  config/Hipcheck.kdl
  plugins/binary/Cargo.toml
  plugins/binary/plugin.kdl
  plugins/binary/src/binary_detector.rs
  plugins/binary/src/error/context.rs
  plugins/binary/src/error/mod.rs
  plugins/binary/src/fs.rs
  plugins/binary/src/main.rs
Labels: type: enhancement

#542 fix: Git log commit parser now returns more than one commit.
  plugins/git/src/parse.rs
Labels: type: bug, product: hc

#535 chore: Adds full org list to example_orgs.kdl in affiliation plugin
  plugins/affiliation/src/org_spec.rs
  plugins/affiliation/test/example_orgs.kdl
  plugins/affiliation/test/test_orgs.kdl
Labels: type: chore, product: project

#523 feat: add churn plugin
  Cargo.lock
  Cargo.toml
  hipcheck/src/engine.rs
  hipcheck/src/plugin/mod.rs
  hipcheck/src/plugin/retrieval.rs
  plugins/churn/Cargo.toml
  plugins/churn/plugin.kdl
  plugins/churn/src/error/context.rs
  plugins/churn/src/error/mod.rs
  plugins/churn/src/linguist/db.rs
  plugins/churn/src/linguist/fs.rs
  plugins/churn/src/linguist/mod.rs
  plugins/churn/src/main.rs
  plugins/churn/src/metric.rs
  plugins/churn/src/types.rs
Labels: type: enhancement, product: rust-sdk
