Repository mitre/hipcheck, pull requests merged in 2025-01, with the labels that each got.

#754 feat: improved version-to-git-tag matching scheme
  hipcheck/src/source/git.rs
  hipcheck/src/target/resolve.rs
  hipcheck/src/target/types.rs
Labels: type: enhancement, product: hc

#767 chore: release blog post for Hipcheck 3.9.1
  dist/Containerfile
  site/config.toml
  site/content/blog/2025-01-08-hipcheck-3.9.1-release.md
  site/static/dl/install.ps1
  site/static/dl/install.sh
  site/static/images/authors/julian.png
Labels: product: project

#772 fix: Update site announce link to 3.9.1
  site/config.toml
Labels: type: chore, product: website

#775 chore: Remove .zed directory
  .gitignore
  .zed/settings.json
Labels: type: chore, product: project

#662 Aamohd/file based config
  config/Exec.kdl
  hipcheck/src/cli.rs
  hipcheck/src/config.rs
  hipcheck/src/engine.rs
  hipcheck/src/exec.rs
  hipcheck/src/main.rs
  hipcheck/src/plugin/manager.rs
  hipcheck/src/plugin/types.rs
  hipcheck/src/session/mod.rs
  site/content/docs/guide/cli/general-flags.md
Labels: type: enhancement, type: ui, product: hc

#796 chore(docs): clean up exposed symbols and doc comments for Rust SDK
  sdk/rust/Cargo.toml
  sdk/rust/src/engine.rs
  sdk/rust/src/error.rs
  sdk/rust/src/lib.rs
  sdk/rust/src/mock.rs
  sdk/rust/src/server.rs
Labels: type: chore, product: rust-sdk

#728 chore(docs): developer docs on plugin system communication
  site/content/docs/contributing/_index.md
  site/content/docs/contributing/developer-docs/_index.md
  site/content/docs/contributing/developer-docs/architecture.md
  site/content/docs/contributing/developer-docs/plugin-query-system/developer_docs_plugin_grpc.drawio
  site/content/docs/contributing/developer-docs/plugin-query-system/developer_docs_plugin_grpc.png
  site/content/docs/contributing/developer-docs/plugin-query-system/developer_docs_plugin_sender_receiver.drawio
  site/content/docs/contributing/developer-docs/plugin-query-system/developer_docs_plugin_sender_receiver.png
  site/content/docs/contributing/developer-docs/plugin-query-system/index.md
  site/content/docs/contributing/developer-docs/repo-structure.md
  site/content/docs/contributing/pr-review.md
Labels: type: chore, product: website

#804 chore: update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: type: chore, product: project

#820 feat: Improve desktop site nav and home.
  site/config.toml
  site/templates/bases/base.tera.html
  site/templates/index.html
  site/templates/macros/breadcrumbs.tera.html
  site/templates/partials/footer.tera.html
  site/templates/partials/install.tera.html
  site/templates/partials/nav.tera.html
Labels: product: website

#816 feat: Add English language parsing of failure messages
  hipcheck/src/policy_exprs/env.rs
  hipcheck/src/policy_exprs/error.rs
  hipcheck/src/policy_exprs/expr.rs
  hipcheck/src/policy_exprs/mod.rs
  hipcheck/src/report/mod.rs
  hipcheck/src/report/report_builder.rs
  hipcheck/src/score.rs
  hipcheck/src/shell/mod.rs
  plugins/activity/src/main.rs
  plugins/affiliation/src/main.rs
  plugins/binary/src/main.rs
  plugins/churn/src/main.rs
  plugins/entropy/src/main.rs
  plugins/fuzz/src/main.rs
  plugins/review/src/main.rs
  plugins/typo/src/main.rs
Labels: type: enhancement, product: hc, product: project, product: plugin

#835 chore: Move target parsing code to target module from session.
  hipcheck/src/cli.rs
  hipcheck/src/session/mod.rs
  hipcheck/src/target/cyclone_dx.rs
  hipcheck/src/target/mod.rs
  hipcheck/src/target/pm.rs
  hipcheck/src/target/purl.rs
  hipcheck/src/target/resolve.rs
  hipcheck/src/target/spdx.rs
  hipcheck/src/target/tests/bats.cdx.json
  hipcheck/src/target/tests/juiceshop_bom.json
  hipcheck/src/target/tests/juiceshop_bom.xml
  hipcheck/src/target/types.rs
Labels: product: hc

#842 fix: Updates indicatif to v. 0.17.11 to resolve thread safety error.
  Cargo.lock
  hipcheck/Cargo.toml
Labels: type: bug, product: hc

#847 fix: Removes panic when looking for multiple versions of the same plugin
  hipcheck/src/plugin/mod.rs
Labels: type: bug, product: hc

#818 feat: implemented delete
  hipcheck/src/cache/plugin.rs
Labels: type: enhancement, type: refactor, product: plugin

#854 chore: bump plugin versions for release
  plugins/activity/plugin.kdl
  plugins/affiliation/plugin.kdl
  plugins/binary/plugin.kdl
  plugins/churn/plugin.kdl
  plugins/entropy/plugin.kdl
  plugins/fuzz/plugin.kdl
  plugins/git/plugin.kdl
  plugins/github/plugin.kdl
  plugins/identity/plugin.kdl
  plugins/linguist/plugin.kdl
  plugins/npm/plugin.kdl
  plugins/review/plugin.kdl
  plugins/typo/plugin.kdl
Labels: type: chore

#865 chore: Bump patch version for Rust SDK
  Cargo.lock
  sdk/rust/Cargo.toml
Labels: type: chore, product: rust-sdk
