Repository mitre/hipcheck, pull requests merged in 2025-04, with the labels that each got.

#1088 chore: add docs describing how to unit-test Rust SDK plugins
  site/content/docs/guide/making-plugins/rust-sdk.md
Labels: type: chore, product: website

#1075 feat: Refactor Session for support of multiple target runs
  hipcheck/src/main.rs
  hipcheck/src/report/mod.rs
  hipcheck/src/report/report_builder.rs
  hipcheck/src/score.rs
  hipcheck/src/session/mod.rs
  hipcheck/src/target/types.rs
  sdk/schema/hipcheck_target_schema.json
Labels: product: hc

#1091 chore: bump python sdk version
  sdk/python/README.md
  sdk/python/docs/source/conf.py
  sdk/python/pyproject.toml
  sdk/python/uv.lock
Labels: type: chore

#1095 feat: basic go.mod parsing and async refactor
  Cargo.lock
  hipcheck/Cargo.toml
  hipcheck/src/session/mod.rs
  hipcheck/src/target/mod.rs
  hipcheck/src/target/multi.rs
  hipcheck/src/target/resolve.rs
  hipcheck/src/target/types.rs
  library/hipcheck-workspace-hack/Cargo.toml
Labels: type: enhancement, product: hc

#1093 chore: add python sdk release announcement blog post
  site/content/blog/2025-04-02-python-sdk-0.2.0-release.md
Labels: type: chore, product: website

#1096 fix: let Python sdk blog post render preview blurb
  site/content/blog/2025-04-02-python-sdk-0.2.0-release.md
Labels: type: chore

#1109 feat: parse package-lock.json npm dependencies to SingleTargetSeeds
  hipcheck/src/cli.rs
  hipcheck/src/target/multi.rs
  hipcheck/src/target/resolve.rs
  hipcheck/src/target/tests/package-lock.json
  hipcheck/src/target/types.rs
Labels: type: enhancement, product: hc

#1114 chore: add exec.kdl file suggestion to plugin spawn failure message
  hipcheck/src/plugin/manager.rs
Labels: type: chore, product: hc

#1099 feat: Add async target analysis
  Cargo.lock
  hipcheck/Cargo.toml
  hipcheck/src/cli.rs
  hipcheck/src/engine/mod.rs
  hipcheck/src/main.rs
  hipcheck/src/session/mod.rs
  hipcheck/src/shell/mod.rs
  hipcheck/src/target/resolve.rs
  site/content/docs/getting-started/install.md
Labels: type: enhancement, product: hc, product: project

#1119 fix: Handle possible error in creating new default tokio runtime
  hipcheck/src/main.rs
Labels: type: bug, product: hc

#1118 chore: bump crate versions ahead of 3.13 release
  Cargo.lock
  hipcheck/Cargo.toml
  library/hipcheck-common/Cargo.toml
  library/hipcheck-sdk-macros/Cargo.toml
  plugins/activity/Cargo.toml
  plugins/affiliation/Cargo.toml
  plugins/binary/Cargo.toml
  plugins/churn/Cargo.toml
  plugins/entropy/Cargo.toml
  plugins/fuzz/Cargo.toml
  plugins/git/Cargo.toml
  plugins/github/Cargo.toml
  plugins/identity/Cargo.toml
  plugins/linguist/Cargo.toml
  plugins/npm/Cargo.toml
  plugins/review/Cargo.toml
  plugins/typo/Cargo.toml
  sdk/rust/Cargo.toml
Labels: type: chore, product: project
