Repository mitre/hipcheck, pull requests merged in 2025-03, with the labels that each got.

#982 chore: Removed unused dependencies.
  Cargo.lock
  hipcheck-common/Cargo.toml
  hipcheck/Cargo.toml
  plugins/activity/Cargo.toml
  plugins/binary/Cargo.toml
  plugins/entropy/Cargo.toml
  plugins/fuzz/Cargo.toml
  plugins/git/Cargo.toml
  plugins/github/Cargo.toml
  plugins/linguist/Cargo.toml
  plugins/typo/Cargo.toml
  sdk/rust/Cargo.toml
  test-plugins/dummy_rand_data/Cargo.toml
Labels: type: chore

#966 chore: Folder reorganization.
  .github/workflows/hipcheck.yml
  Cargo.toml
  hipcheck/Cargo.toml
  library/hipcheck-common/Cargo.toml
  library/hipcheck-common/build.rs
  library/hipcheck-common/proto/hipcheck/v1/hipcheck.proto
  library/hipcheck-common/src/chunk.rs
  library/hipcheck-common/src/error.rs
  library/hipcheck-common/src/lib.rs
  library/hipcheck-common/src/types.rs
  library/hipcheck-kdl/Cargo.toml
  library/hipcheck-kdl/src/lib.rs
  library/hipcheck-macros/Cargo.toml
  library/hipcheck-macros/README.md
  library/hipcheck-macros/src/lib.rs
  library/hipcheck-macros/src/update.rs
  library/hipcheck-sdk-macros/Cargo.toml
  library/hipcheck-sdk-macros/src/lib.rs
  plugins/affiliation/Cargo.toml
  plugins/binary/Cargo.toml
  plugins/linguist/Cargo.toml
  plugins/typo/Cargo.toml
  proto/hipcheck/v1/messages/default_policy_expr_request.proto
  proto/hipcheck/v1/messages/default_policy_expr_response.proto
  proto/hipcheck/v1/messages/empty.proto
  proto/hipcheck/v1/messages/explain_default_query_request.proto
  proto/hipcheck/v1/messages/explain_default_query_response.proto
  proto/hipcheck/v1/messages/query.proto
  proto/hipcheck/v1/messages/query_request.proto
  proto/hipcheck/v1/messages/query_response.proto
  proto/hipcheck/v1/messages/query_schemas_request.proto
  proto/hipcheck/v1/messages/query_schemas_response.proto
  proto/hipcheck/v1/messages/query_state.proto
  proto/hipcheck/v1/messages/set_config_request.proto
  proto/hipcheck/v1/messages/set_config_response.proto
  proto/hipcheck/v1/plugin_service.proto
  sdk/rust/Cargo.toml
  site/content/docs/contributing/developer-docs/repo-structure.md
  tests/test-plugins/dummy_rand_data/Cargo.toml
  tests/test-plugins/dummy_rand_data/src/main.rs
  tests/test-plugins/dummy_sha256/Cargo.toml
  tests/test-plugins/dummy_sha256/schema/query_schema_sha256.json
  tests/test-plugins/dummy_sha256/src/main.rs
Labels: type: chore

#992 Introduce 'workspace-hack' crate.
  .config/hakari.toml
  .github/workflows/hipcheck.yml
  Cargo.lock
  Cargo.toml
  hipcheck/Cargo.toml
  library/hipcheck-common/Cargo.toml
  library/hipcheck-kdl/Cargo.toml
  library/hipcheck-macros/Cargo.toml
  library/hipcheck-sdk-macros/Cargo.toml
  library/hipcheck-workspace-hack/.gitattributes
  library/hipcheck-workspace-hack/Cargo.toml
  library/hipcheck-workspace-hack/build.rs
  library/hipcheck-workspace-hack/src/lib.rs
  plugins/activity/Cargo.toml
  plugins/affiliation/Cargo.toml
  plugins/binary/Cargo.toml
  plugins/churn/Cargo.toml
  plugins/entropy/Cargo.toml
  plugins/fuzz/Cargo.toml
  plugins/git/Cargo.toml
  plugins/github/Cargo.toml
  plugins/identity/Cargo.toml
  plugins/linguist/Cargo.toml
  plugins/npm/Cargo.toml
  plugins/review/Cargo.toml
  plugins/typo/Cargo.toml
  sdk/rust/Cargo.toml
  sdk/schema/hipcheck_target_schema.json
  tests/test-plugins/dummy_rand_data/Cargo.toml
  tests/test-plugins/dummy_sha256/Cargo.toml
  xtask/Cargo.toml
Labels: type: chore, product: project

#998 fix: Binary plugin now correctly matches file extension strings
  Cargo.lock
  plugins/binary/Cargo.toml
  plugins/binary/plugin.kdl
  plugins/binary/src/binary_detector.rs
Labels: type: bug, product: plugin

#1017 fix: Improves english message when missing default explanation
  hipcheck/src/report/report_builder.rs
  library/hipcheck-workspace-hack/Cargo.toml
Labels: type: bug, product: hc, product: plugin

#993 Fix x-padding on website index page.
  site/templates/bases/base.tera.html
  site/templates/index.html
  site/templates/partials/footer.tera.html
  site/templates/partials/nav.tera.html
Labels: type: bug, product: website

#1011 feat(xtask): xtask validates Python projects
  Cargo.lock
  library/hipcheck-workspace-hack/Cargo.toml
  sdk/python/LICENSE.md
  sdk/python/pyproject.toml
  xtask/Cargo.toml
  xtask/src/build.rs
  xtask/src/string.rs
  xtask/src/task/validate.rs
Labels: product: project, product: python-sdk

#1007 feat: bidirectional query protocol with chunking in Python SDK
  library/hipcheck-common/src/chunk.rs
  library/hipcheck-common/src/types.rs
  sdk/python/LICENSE
  sdk/python/README.md
  sdk/python/pyproject.toml
  sdk/python/src/hipcheck_sdk/__init__.py
  sdk/python/src/hipcheck_sdk/chunk.py
  sdk/python/src/hipcheck_sdk/engine.py
  sdk/python/src/hipcheck_sdk/error.py
  sdk/python/src/hipcheck_sdk/gen/__init__.py
  sdk/python/src/hipcheck_sdk/gen/hipcheck_pb2.py
  sdk/python/src/hipcheck_sdk/gen/hipcheck_pb2_grpc.py
  sdk/python/src/hipcheck_sdk/options.py
  sdk/python/src/hipcheck_sdk/query.py
  sdk/python/src/hipcheck_sdk/server.py
  sdk/python/tests/context.py
  sdk/python/tests/example-plugin/main.py
  sdk/python/tests/example-plugin/run.sh
  sdk/python/tests/test_chunk.py
  sdk/python/tests/test_mock_responses.py
  sdk/python/uv.lock
  sdk/rust/src/engine.rs
Labels: type: enhancement, product: python-sdk

#1028 feat: Replace rustls-navtive-certs with rustls-platform-verifier
  Cargo.lock
  hipcheck/Cargo.toml
  hipcheck/src/util/http/agent.rs
  library/hipcheck-workspace-hack/Cargo.toml
  plugins/github/Cargo.toml
  plugins/github/src/util/agent.rs
  xtask/Cargo.toml
  xtask/src/task/manifest/util/agent.rs
Labels: type: enhancement, product: hc, product: project, product: plugin

#963 feat: add RFD describing support for multi-repo target
  site/content/docs/rfds/0011-lock-file-target.md
Labels: product: project

#1044 chore: Update tagline on site index
  site/templates/bases/base.tera.html
  site/templates/index.html
Labels: type: chore, product: website

#1066 chore: move plugin query trace log to engine.rs from plugins
  plugins/activity/src/main.rs
  plugins/affiliation/src/main.rs
  plugins/churn/src/main.rs
  plugins/entropy/src/main.rs
  plugins/fuzz/src/main.rs
  plugins/identity/src/main.rs
  plugins/review/src/main.rs
  plugins/typo/src/main.rs
  sdk/rust/src/engine.rs
  sdk/rust/src/lib.rs
Labels: type: chore, product: rust-sdk, product: plugin

#1032 chore: write RFD for expecting set_config hash
  site/content/docs/rfds/0011-lock-file-target.md
  site/content/docs/rfds/0013-plugin-config-hash.md
Labels: type: chore, product: hc, product: rust-sdk, product: python-sdk
