Repository mitre/hipcheck, pull requests merged in 2025-02, with the labels that each got.

#866 chore: Announcement blog post for 3.10.0
  site/config.toml
  site/content/blog/2025-01-31-hipcheck-3.10.0-release.md
Labels: type: chore

#872 feat: Adds English language parsing for successful analyses
  hipcheck/src/policy_exprs/env.rs
  hipcheck/src/policy_exprs/mod.rs
  hipcheck/src/report/mod.rs
  hipcheck/src/shell/mod.rs
Labels: type: enhancement, product: hc, product: project

#874 chore(docs): add description of the Query protocol
  site/content/docs/guide/making-plugins/_index.md
  site/content/docs/guide/making-plugins/query-protocol.md
  site/content/docs/guide/making-plugins/release.md
Labels: type: chore, product: project

#877 feat: change churn and entropy plugins to send batch queries to linguist
  Cargo.lock
  config/local.Hipcheck.kdl
  config/local.release.Hipcheck.kdl
  plugins/churn/Cargo.toml
  plugins/churn/local-plugin.kdl
  plugins/churn/local-release-plugin.kdl
  plugins/churn/plugin.kdl
  plugins/churn/src/linguist.rs
  plugins/churn/src/main.rs
  plugins/churn/src/metric.rs
  plugins/churn/src/util/db.rs
  plugins/churn/src/util/fs.rs
  plugins/churn/src/util/kdl.rs
  plugins/churn/src/util/mod.rs
  plugins/entropy/Cargo.toml
  plugins/entropy/local-plugin.kdl
  plugins/entropy/local-release-plugin.kdl
  plugins/entropy/plugin.kdl
  plugins/entropy/src/linguist.rs
  plugins/entropy/src/main.rs
  plugins/entropy/src/metric.rs
  plugins/entropy/src/util/db.rs
  plugins/entropy/src/util/fs.rs
  plugins/entropy/src/util/kdl.rs
  plugins/entropy/src/util/mod.rs
  plugins/linguist/src/main.rs
Labels: type: enhancement

#885 feat: Improve English phrasing of count and percent policy expressions.
  hipcheck/src/policy_exprs/mod.rs
  plugins/churn/src/main.rs
  plugins/entropy/src/main.rs
Labels: product: hc, product: plugin

#916 chore: add policy location info to standard check output
  hipcheck/src/session/mod.rs
  hipcheck/src/shell/mod.rs
Labels: product: hc

#917 feat: make Exec.kdl defaults os-aware
  hipcheck/src/exec.rs
Labels: product: hc

#912 chore: "Maximum Configurability" blog post
  site/content/blog/2025-02-11-hipchecks-ramp-of-maximum-configurability.md
Labels: product: website

#937 feat: Prints human output directly from Report
  Cargo.lock
  hipcheck/Cargo.toml
  hipcheck/src/report/mod.rs
  hipcheck/src/shell/mod.rs
Labels: type: ui, product: hc

#946 chore: update versions of libraries and plugins ahead of 3.11 release
  Cargo.lock
  hipcheck-common/Cargo.toml
  hipcheck-sdk-macros/Cargo.toml
  hipcheck/Cargo.toml
  plugins/activity/Cargo.toml
  plugins/activity/plugin.kdl
  plugins/affiliation/Cargo.toml
  plugins/affiliation/plugin.kdl
  plugins/binary/Cargo.toml
  plugins/binary/plugin.kdl
  plugins/churn/Cargo.toml
  plugins/churn/plugin.kdl
  plugins/entropy/Cargo.toml
  plugins/entropy/plugin.kdl
  plugins/fuzz/Cargo.toml
  plugins/fuzz/plugin.kdl
  plugins/git/Cargo.toml
  plugins/git/plugin.kdl
  plugins/github/Cargo.toml
  plugins/github/plugin.kdl
  plugins/identity/Cargo.toml
  plugins/identity/plugin.kdl
  plugins/linguist/Cargo.toml
  plugins/linguist/plugin.kdl
  plugins/npm/Cargo.toml
  plugins/npm/plugin.kdl
  plugins/review/Cargo.toml
  plugins/review/plugin.kdl
  plugins/typo/Cargo.toml
  plugins/typo/plugin.kdl
  sdk/rust/Cargo.toml
Labels: product: project

#902 feat: first version of listing and deleting plugins with CLI
  hipcheck/src/cache/plugin.rs
  hipcheck/src/cli.rs
  hipcheck/src/main.rs
Labels: type: ui, product: hc

#961 feat: update and sync runners (ubuntu-22.04, macos-14)
  .github/workflows/hipcheck.yml
  dist-workspace.toml
Labels: type: enhancement
